language: python
python:
  - 2.7
install:
  - pip install numpy --upgrade
  - pip install nupic
  - pip install -r requirements.txt

# Run tests
script:
  - py.test tests/

# Whitelist branches
branches:
  only:
    - master